module.exports = {
  content: [
    './templates/**/*.html',
    './**/templates/**/*.html',
    './static/**/*.js',
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "#ffddb0",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#614000",
        "surface-container-high": "#e7e9e5",
        "on-tertiary-container": "#e9a52a",
        "surface-tint": "#2b6954",
        "background": "#f8faf6",
        "inverse-primary": "#95d3ba",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5d5f5e",
        "tertiary": "#412900",
        "on-primary-fixed": "#002117",
        "on-secondary-fixed-variant": "#454747",
        "surface-dim": "#d8dbd7",
        "secondary-fixed-dim": "#c6c7c6",
        "primary-fixed": "#b0f0d6",
        "on-secondary-container": "#616362",
        "primary-container": "#064e3b",
        "on-tertiary-fixed": "#281800",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#0b513d",
        "surface": "#f8faf6",
        "surface-variant": "#e1e3e0",
        "on-surface-variant": "#404944",
        "surface-container-highest": "#e1e3e0",
        "outline-variant": "#bfc9c3",
        "secondary-container": "#dfe0df",
        "on-primary-container": "#80bea6",
        "inverse-surface": "#2e312f",
        "inverse-on-surface": "#eff1ee",
        "tertiary-fixed-dim": "#ffba46",
        "primary": "#003527",
        "on-surface": "#191c1b",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f1",
        "primary-fixed-dim": "#95d3ba",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#eceeeb",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#ffffff",
        "surface-bright": "#f8faf6",
        "on-background": "#191c1b",
        "on-error-container": "#93000a",
        "outline": "#707974",
        "error-container": "#ffdad6",
        "tertiary-container": "#5e3e00"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "margin-mobile": "16px",
        "base": "8px",
        "margin-desktop": "48px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "headline-sm": ["EB Garamond", "serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "label-md": ["Work Sans", "sans-serif"],
        "headline-lg": ["Libre Caslon Text", "serif"]
      },
      "fontSize": {
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "500"}],
        "display-lg-mobile": ["36px", {"lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}]
      },
      "boxShadow": {
        'level-1': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'level-2': '0px 4px 20px rgba(6, 78, 59, 0.05)',
      }
    }
  },
  plugins: [],
}
