# Generated by Django 6.0.5 on 2026-05-21 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('course_type', models.CharField(choices=[('physical', 'Physical In-Person Class'), ('online', 'Online Pre-recorded Class')], default='physical', max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in UGX', max_digits=10)),
                ('video_url', models.URLField(blank=True, help_text='Secure video link (e.g. Mux/Vimeo)', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum number of attendees')),
                ('attendees_count', models.PositiveIntegerField(default=0, help_text='Current number of bookings')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes.course')),
            ],
        ),
    ]
