# Generated by Django 5.2.6 on 2026-05-22 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_course_video_url_course_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioRentalPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=50000, help_text='Hourly rental rate in UGX', max_digits=10)),
                ('min_hours', models.PositiveIntegerField(default=2, help_text='Minimum hours required to book')),
            ],
        ),
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField(help_text='Brief description of the rental purpose (e.g. food photography, test kitchen)')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved (Awaiting Payment)'), ('paid', 'Paid & Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
