# Generated by Django 5.2.6 on 2026-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.CharField(default='Turn Everyday Cooking into Everyday Magic!', max_length=255)),
                ('hero_video_url', models.URLField(blank=True, help_text='Direct link to mp4 video for the hero background', null=True)),
                ('nurses_note', models.TextField(default='Tomatoes are rich in Lycopene...', help_text='Note to include in digital downloads and about section')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
