# Generated by Django 5.2.6 on 2026-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_newslettersubscriber_id_alter_sitesettings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_video_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Fallback hero image (used if video fails or on mobile)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload an mp4 video for the hero background', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
