# Generated by Django 6.0.5 on 2026-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_sitesettings_hero_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_youtube_embed_url',
            field=models.URLField(blank=True, default='', help_text='Paste a YouTube video URL to embed (e.g. https://youtube.com/watch?v=...)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_loop_words',
            field=models.CharField(blank=True, default='Healing, Art, Joy, Nourishment', help_text="Comma-separated keywords for the typewriter loop (e.g. 'Healing, Art, Joy')", max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_lead_magnet',
            field=models.FileField(blank=True, help_text='Upload a free PDF to offer subscribers as incentive', null=True, upload_to='site/lead_magnets/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_lead_magnet_title',
            field=models.CharField(blank=True, default='Free Wholesome Recipe Guide', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nurse_bio',
            field=models.TextField(blank=True, default='', help_text='Short bio for the Meet the Nurse section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nurse_name',
            field=models.CharField(blank=True, default='The Cooking Nurse', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nurse_portrait',
            field=models.ImageField(blank=True, help_text='Portrait photo', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
