# Generated by Django 5.2.6 on 2026-05-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_sitesettings_featured_youtube_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cooking_classes_image',
            field=models.ImageField(blank=True, help_text='Image for the Cooking Classes card', null=True, upload_to='site/cards/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='digital_library_image',
            field=models.ImageField(blank=True, help_text='Image for the Digital Library card', null=True, upload_to='site/cards/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='studio_rental_image',
            field=models.ImageField(blank=True, help_text='Image for the Studio Rental card', null=True, upload_to='site/cards/'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
