# Generated by Django 6.0.5 on 2026-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_sitesettings_cooking_classes_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_about_subtitle',
            field=models.TextField(default='Step into a sensory kitchen designed to feed your soul, strengthen your body, and inspire your everyday meals.', help_text='Subtitle/description for the Experience section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_about_title',
            field=models.CharField(default='Experience The Cooking Nurse', help_text='Title for the Experience section', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nurse_subtitle',
            field=models.TextField(default='Discover the healing culinary philosophy, medical nutrition background, and heart-led mission of the nurse blending clinical science with sensory kitchen joy.', help_text='Introductory subtitle for the Meet the Chef section'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
