# Generated by Django 6.0.5 on 2026-05-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address',
            new_name='landmark_or_building',
        ),
    ]
