# Generated by Django 5.2.6 on 2026-05-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(blank=True, help_text='Fallback text address', max_length=255, null=True),
        ),
    ]
